#!/usr/bin/env bash

##################################################
# Ubuntu installer Helper
# Authtor: Oliver Buchmann <o.buch91@gmail.com>
##################################################

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

declare -a packages=(
	base
	dev
)	

for package in "${packages[@]}"; do

	if [ -f "$DIR/$package/install.sh" ]; then
		echo "Running installer for package $package"
		bash -c "$DIR/$package/install.sh"
	fi

done